### ISSUE TITLE
Why min deployment target is 8

### ISSUE THREAD

**Issue by badeleux** [Draveness/Snake#1]
^

**Comment by draveness** [comment]
This is a Swift repo

**Comment by badeleux** [comment]
Aaaand? Swift is compatible with iOS 7

**Comment by draveness** [comment]
I just do not want to update this repo, are u using this one? Why not star it?

**Comment by badeleux** [comment]
Let me do pull request with iOS 7 and swift 2 compatibility.

**Comment by draveness** [comment]
Great, I will add u to this repo

**Comment by draveness** [comment]
Swift support uses dynamic frameworks and is therefore only supported on iOS > 8

**Comment by badeleux** [comment]
Yeah, I saw this. It's because of cocoa pods. Let me update pod spec, and update cocoa pods repo with new version with swift2 fixes.
